version: 2.1
jobs:
  extract-catalog:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - run: 
          name: install raptor-utils
          command: | 
            sudo apt-get update -y 
            sudo apt-get install -y raptor2-utils
      - run: mkdir -p /tmp/workspace/target
      - run:
          name: download-vodap
          command: |
            ~/project/scripts/download.sh " https://metadata.vlaanderen.be/srv/api/records?hitsPerPage=100&from=1&to=100&facet.q=isOpenData%2Fy" /tmp/workspace/target/vodap.nt
      - run:
          name: cleanup all non-parseable triples
          command: if rapper -i ntriples /tmp/workspace/target/vodap.nt > /tmp/workspace/target/cleaned.nt ; then echo "no error found" ; else echo "ERRORS FOUND" ; fi 
      - run:
          name: gzip all files
          command: gzip /tmp/workspace/target/*
      - run:
          name: List the files which have been created
          command: ls -al /tmp/workspace/*
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/
  create-artifact:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "07:1f:53:70:b5:9e:a1:d3:f0:2c:be:9b:ec:c8:d7:43"
      - run:
          name: Checkout target repo
          workdir: /tmp
          command: |
            rm -rf generated
            git clone git@github.com:Informatievlaanderen/vodap.git generated
      - run:
          name: Switch to the target directory
          workdir: /tmp/generated
          command: |
            git fetch origin
            git checkout -b "vodap-${CIRCLE_BRANCH}" --track "origin/vodap-${CIRCLE_BRANCH}"
      - run:
          name: Copy assets
          workdir: /tmp/workspace
          command: |
            cp -R target/vodap.nt.gz /tmp/generated/
            cp -R target/cleaned.nt.gz /tmp/generated/
      - run:
          name: Push results to github
          workdir: /tmp/generated
          command: |
            git config user.email "circleci@data.vlaanderen.be"
            git config user.name "Circle CI Builder"
            git add .
            git commit -m "Applying changes from commit ${CIRCLE_SHA1}" --allow-empty
            git push origin "vodap-${CIRCLE_BRANCH}"
workflows:
  version: 2
  generate_documentation:
    jobs:
      - extract-catalog
      - create-artifact:
          requires:
            - extract-catalog
